{% set name = "toml" %}
{% set version = "0.9.3.1" %}
{% set hash_type = "sha256" %}
{% set hash = "e1e8c220046889234df5ec688d6f97b734fc4a08a6d8edfc176f4e6abf90cfb5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 1
  noarch: python
  script: python setup.py install --record=record.txt

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - toml

about:
  home: https://github.com/uiri/toml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python lib for TOML.'

extra:
  recipe-maintainers:
    - rlaverde
