{% set name = "toml" %}
{% set version = "0.10.2" %}
{% set sha256 = "b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  noarch: {{ noarch_python }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - toml

about:
  home: https://github.com/uiri/toml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python lib for TOML.'

extra:
  recipe-maintainers:
    - rlaverde
    - holgern
