{% set name = "toml" %}
{% set version = "0.9.3.1" %}
{% set sha256 = "e1e8c220046889234df5ec688d6f97b734fc4a08a6d8edfc176f4e6abf90cfb5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 2
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - toml
  commands:
    - conda inspect linkages -p $PREFIX toml  # [not win]
    - conda inspect objects -p $PREFIX toml   # [osx]

about:
  home: https://github.com/uiri/toml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python lib for TOML.'

extra:
  recipe-maintainers:
    - rlaverde
